title: Harry Ray - Jekyll Portfolio
author: Harry Ray
email: harry@harry-ray.com
description: >- # this means to ignore newlines until "baseurl:"
  This the the Jekyll portion of my portfolio. This site is
  built with Liquid and Sass, uses Jekyll to compile everything, using Terminal to run and test
  on localhost and push up to Github. From there, it's automatically
  deployed to Netlify.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  harryray

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
